//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 12/26/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class StyleKitName : NSObject {

    //// Drawing Methods

    public class func drawCanvas1(frameValue frameValue: CGRect = CGRectMake(0, 0, 240, 120), circlePadding: CGFloat = 0, strokeWidth: CGFloat = 2) {

        //// Variable Declarations
        let minEdge: CGFloat = round(min(frameValue.size.width, frameValue.size.height))
        let circleDiameter: CGFloat = minEdge - circlePadding * 2 - strokeWidth
        let circlePaddingX: CGFloat = round((frameValue.size.width - circleDiameter) / 2.0)
        let circlePaddingY: CGFloat = round((frameValue.size.height - circleDiameter) / 2.0)

        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRectMake(circlePaddingX, circlePaddingY, circleDiameter, circleDiameter))
        UIColor.grayColor().setFill()
        ovalPath.fill()
        UIColor.redColor().setStroke()
        ovalPath.lineWidth = strokeWidth
        ovalPath.stroke()
    }

}
